import { initializeApp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import { getFirestore, collection, getDocs, getDoc, doc, setDoc, updateDoc, deleteDoc, query, limit, serverTimestamp, Timestamp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const provider = new GoogleAuthProvider();
const ADMIN_UID = "ANzaRtHgkJXlcPO8NmhzuAJ0b5C3";
const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = v => Number.isFinite(Number(v)) ? `₹${Number(v).toLocaleString('en-IN')}` : '—';
const dateText = v => { try { if (!v) return '—'; const d = v.toDate ? v.toDate() : new Date(v); return Number.isNaN(d.getTime()) ? '—' : d.toLocaleDateString('en-IN'); } catch { return '—'; } };
const dateTimeText = v => { try { if (!v) return '—'; const d = v.toDate ? v.toDate() : new Date(v); return Number.isNaN(d.getTime()) ? '—' : d.toLocaleString('en-IN'); } catch { return '—'; } };
const ts = v => { const d = new Date(v); return Number.isNaN(d.getTime()) ? null : Timestamp.fromDate(d); };
function nav(id){ document.querySelectorAll('.section').forEach(x=>x.classList.add('hidden')); $(id)?.classList.remove('hidden'); document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===id)); }
function badge(v){ const s=String(v||'UNKNOWN').toUpperCase(); const c=s==='ACTIVE'||s==='AVAILABLE'?'active':s==='EXPIRED'||s==='SUSPENDED'||s==='REVOKED'?'expired':'pending'; return `<span class="badge ${c}">${esc(s)}</span>`; }
function toast(m,t='success'){ document.querySelector('.toast')?.remove(); const e=document.createElement('div'); e.className=`toast ${t}`; e.textContent=m; document.body.appendChild(e); setTimeout(()=>e.remove(),2800); }
async function adminOK(u){ if(!u) return false; const s=await getDoc(doc(db,'admins',u.uid)); return s.exists() && s.data().active===true && u.uid===ADMIN_UID; }

async function deleteSubcollection(parentCollection, parentId, subcollection){
  const snap = await getDocs(query(collection(db,parentCollection,parentId,subcollection),limit(500)));
  await Promise.all(snap.docs.map(d=>deleteDoc(d.ref)));
}
async function deleteCollection(name){
  const snap = await getDocs(query(collection(db,name),limit(500)));
  for(const d of snap.docs){
    if(name==='customers') await deleteSubcollection('customers', d.id, 'devices');
    if(name==='devices') await deleteSubcollection('devices', d.id, 'sessions');
  }
  await Promise.all(snap.docs.map(d=>deleteDoc(d.ref)));
}

async function initializeDatabase(){
  const now = serverTimestamp();
  await Promise.all([
    setDoc(doc(db,'customers','_meta'),{system:true,collection:'customers',updatedAt:now},{merge:true}),
    setDoc(doc(db,'plans','_meta'),{system:true,collection:'plans',updatedAt:now},{merge:true}),
    setDoc(doc(db,'activationKeys','_meta'),{system:true,collection:'activationKeys',updatedAt:now},{merge:true}),
    setDoc(doc(db,'settings','general'),{appName:'MEESHO A+ LISTING AUTOMATION PRO',brandName:'Sohel Enterprise',supportName:'Sohel Rana',updatedAt:now},{merge:true})
  ]);
  const defaults=[['monthly','Monthly',30,1],['yearly','Yearly',365,2],['lifetime','Lifetime',0,3]];
  for(const [id,name,days,order] of defaults){
    const s=await getDoc(doc(db,'plans',id));
    if(!s.exists()) await setDoc(doc(db,'plans',id),{name,price:0,offerPrice:0,durationDays:days,displayOrder:order,deviceLimit:3,shippingEnabled:true,active:true,createdAt:now,updatedAt:now});
  }
  toast('Clean database structure is ready.');
  await refreshAll();
}

async function cleanLegacyAndInitialize(){
  const ok=confirm('This will DELETE all non-admin legacy data: users, customers, plans, activationKeys, memberships, devices, payments, promoCodes, settings and schema. The admins collection will NOT be touched. Continue?');
  if(!ok) return;
  try{
    const legacy=['users','customers','plans','activationKeys','memberships','devices','payments','promoCodes','settings','schema'];
    for(const c of legacy) await deleteCollection(c);
    await initializeDatabase();
    toast('Legacy data removed and new structure initialized.');
  }catch(e){ console.error(e); toast(e.message||'Cleanup failed.','error'); }
}

async function loadDashboard(){
  const [cs,ks,ps]=await Promise.all([
    getDocs(query(collection(db,'customers'),limit(500))),
    getDocs(query(collection(db,'activationKeys'),limit(500))),
    getDocs(query(collection(db,'plans'),limit(500)))
  ]);
  const customers=cs.docs.filter(d=>!d.data().system), keys=ks.docs.filter(d=>!d.data().system), plans=ps.docs.filter(d=>!d.data().system);
  let active=0,expired=0,lifetime=0,available=0,redeemed=0;
  customers.forEach(s=>{const d=s.data();const st=String(d.status||'').toUpperCase(); if(st==='ACTIVE'){const life=Number(d.durationDays||0)===0;const exp=d.expiryDate?.toDate?d.expiryDate.toDate():d.expiryDate?new Date(d.expiryDate):null;if(life||!exp||exp>Date.now())active++;else expired++;if(life)lifetime++;} else if(st==='EXPIRED') expired++;});
  keys.forEach(s=>{const st=String(s.data().status||'').toUpperCase();if(st==='AVAILABLE')available++;if(st==='REDEEMED')redeemed++;});
  $('dashboard').innerHTML=`<div class="page-head"><div><h2>Dashboard</h2><p class="muted">Email-primary membership system</p></div><div class="head-actions"><button id="initDb" class="primary compact-btn">Initialize</button><button id="cleanDb" class="danger-outline compact-btn">Clean Legacy Data</button></div></div><div class="grid"><div class="stat"><span>Customers</span><b>${customers.length}</b></div><div class="stat"><span>Active Members</span><b>${active}</b></div><div class="stat"><span>Expired</span><b>${expired}</b></div><div class="stat"><span>Lifetime</span><b>${lifetime}</b></div><div class="stat"><span>Available Keys</span><b>${available}</b></div><div class="stat"><span>Redeemed Keys</span><b>${redeemed}</b></div><div class="stat"><span>Active Plans</span><b>${plans.filter(s=>s.data().active!==false).length}</b></div><div class="stat"><span>Device Model</span><b>Email</b></div></div><div class="schema-panel"><strong>Source of truth</strong><div class="inline-note">Customer ID = normalized email. Devices live under customers/{email}/devices. Firebase UID is metadata only and is never the membership key.</div></div>`;
  $('initDb').onclick=initializeDatabase; $('cleanDb').onclick=cleanLegacyAndInitialize;
}

async function loadCustomers(){
  const snap=await getDocs(query(collection(db,'customers'),limit(500))); const rows=[];
  for(const s of snap.docs.filter(x=>!x.data().system)){
    const d=s.data(); let used=0; try{const ds=await getDocs(query(collection(db,'customers',s.id,'devices'),limit(50))); ds.forEach(x=>{if(String(x.data().status||'ACTIVE').toUpperCase()==='ACTIVE')used++;});}catch{}
    rows.push({id:s.id,d,used});
  }
  rows.sort((a,b)=>a.id.localeCompare(b.id));
  $('customers').innerHTML=`<div class="page-head"><div><h2>Customers</h2><p class="muted">Email is the permanent account key.</p></div><button id="customersRefresh" class="ghost">Refresh</button></div><div class="panel"><table class="table"><thead><tr><th>Gmail</th><th>Plan</th><th>Status</th><th>Expiry</th><th>Devices</th><th>Limit</th><th>Action</th></tr></thead><tbody>${rows.map(x=>{const d=x.d;return `<tr><td><strong>${esc(x.id)}</strong></td><td>${esc(d.planName||d.planId||'—')}</td><td>${badge(d.status||'NOT_ACTIVATED')}</td><td>${Number(d.durationDays||0)===0?'NEVER':esc(dateText(d.expiryDate))}</td><td>${x.used}</td><td><div class="limit-editor"><button data-email="${esc(x.id)}" class="limitMinus">−</button><input value="${Math.max(1,Math.min(20,Number(d.deviceLimit||3)))}" data-email="${esc(x.id)}" class="limitInput" inputmode="numeric"><button data-email="${esc(x.id)}" class="limitPlus">+</button></div></td><td><button data-email="${esc(x.id)}" class="customerToggle">${String(d.status||'').toUpperCase()==='SUSPENDED'?'Unsuspend':'Suspend'}</button></td></tr>`}).join('')||'<tr><td colspan="7">No customers yet.</td></tr>'}</tbody></table></div>`;
  $('customersRefresh').onclick=loadCustomers;
  document.querySelectorAll('.limitMinus').forEach(b=>b.onclick=()=>changeLimit(b.dataset.email,-1)); document.querySelectorAll('.limitPlus').forEach(b=>b.onclick=()=>changeLimit(b.dataset.email,1)); document.querySelectorAll('.limitInput').forEach(i=>i.onchange=()=>setLimit(i.dataset.email,i.value));
  document.querySelectorAll('.customerToggle').forEach(b=>b.onclick=async()=>{const ref=doc(db,'customers',b.dataset.email);const s=await getDoc(ref);if(!s.exists())return;const st=String(s.data().status||'').toUpperCase();await updateDoc(ref,{status:st==='SUSPENDED'?'ACTIVE':'SUSPENDED',updatedAt:serverTimestamp()});toast('Customer status updated.');loadCustomers();});
}
async function setLimit(email,value){const n=Math.max(1,Math.min(20,Number(value)||1));await updateDoc(doc(db,'customers',email),{deviceLimit:n,deviceLimitUpdatedAt:serverTimestamp(),deviceLimitUpdatedBy:auth.currentUser?.uid||''});toast(`Device limit set to ${n}.`);loadCustomers();}
async function changeLimit(email,delta){const s=await getDoc(doc(db,'customers',email));if(!s.exists())return;const n=Math.max(1,Math.min(20,Number(s.data().deviceLimit||3)+delta));if(n!==Number(s.data().deviceLimit||3))await setLimit(email,n);}

function planEditor(existing={}){return `<div class="panel form-panel"><div class="panel-title"><div><h3>${existing.id?'Edit Plan':'Create Plan'}</h3><p class="muted">Pricing is controlled only here.</p></div><button id="cancelPlan" class="ghost">Cancel</button></div><form id="planForm" class="form-grid"><label>Plan ID<input id="planId" required ${existing.id?'readonly':''} value="${esc(existing.id||'')}" placeholder="monthly"></label><label>Plan Name<input id="planName" required value="${esc(existing.name||'')}" placeholder="Monthly"></label><label>Price (₹)<input id="price" type="number" min="0" value="${esc(existing.price??0)}" required></label><label>Offer Price (₹)<input id="offerPrice" type="number" min="0" value="${esc(existing.offerPrice??0)}" required></label><label>Duration (Days)<input id="days" type="number" min="0" value="${esc(existing.durationDays??30)}" required></label><label>Device Limit<input id="planDeviceLimit" type="number" min="1" max="20" value="${esc(existing.deviceLimit??3)}"></label><label>Display Order<input id="order" type="number" min="0" value="${esc(existing.displayOrder??0)}"></label><label class="check-row"><input id="planActive" type="checkbox" ${existing.active!==false?'checked':''}> Active</label><label class="check-row"><input id="shippingEnabled" type="checkbox" ${existing.shippingEnabled!==false?'checked':''}> Shipping Included</label><div class="form-actions"><button class="primary small-btn" type="submit">Save Plan</button></div></form></div>`;}
async function loadPlans(){const snap=await getDocs(query(collection(db,'plans'),limit(500)));const plans=snap.docs.filter(s=>!s.data().system).map(s=>({id:s.id,...s.data()})).sort((a,b)=>Number(a.displayOrder||0)-Number(b.displayOrder||0));const rows=plans.map(d=>`<tr><td><code>${esc(d.id)}</code></td><td><strong>${esc(d.name||'—')}</strong></td><td>${money(d.price)}</td><td>${money(d.offerPrice)}</td><td>${d.durationDays==0?'Lifetime':esc(d.durationDays+' days')}</td><td>${esc(d.deviceLimit||3)}</td><td>${badge(d.active===false?'DISABLED':'ACTIVE')}</td><td><button class="editPlan" data-id="${esc(d.id)}">Edit</button> <button class="deletePlan danger-outline" data-id="${esc(d.id)}">Delete</button></td></tr>`).join('');$('plans').innerHTML=`<div class="page-head"><div><h2>Plans</h2><p class="muted">Monthly / Yearly / Lifetime</p></div><div class="head-actions"><button id="newPlan" class="primary compact-btn">+ Add Plan</button><button id="plansRefresh" class="ghost">Refresh</button></div></div><div id="planEditor"></div><div class="panel"><table class="table"><thead><tr><th>ID</th><th>Name</th><th>Price</th><th>Offer</th><th>Duration</th><th>Devices</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows||'<tr><td colspan="8">No plans.</td></tr>'}</tbody></table></div>`;$('plansRefresh').onclick=loadPlans;$('newPlan').onclick=()=>openPlan({});document.querySelectorAll('.editPlan').forEach(b=>b.onclick=async()=>{const s=await getDoc(doc(db,'plans',b.dataset.id));if(s.exists())openPlan({id:s.id,...s.data()});});document.querySelectorAll('.deletePlan').forEach(b=>b.onclick=async()=>{if(!confirm(`Delete plan ${b.dataset.id}?`))return;await deleteDoc(doc(db,'plans',b.dataset.id));toast('Plan deleted.');loadPlans();});}
function openPlan(existing){$('planEditor').innerHTML=planEditor(existing);$('cancelPlan').onclick=()=>$('planEditor').innerHTML='';$('planForm').onsubmit=async e=>{e.preventDefault();const id=$('planId').value.trim().toLowerCase();const data={name:$('planName').value.trim(),price:Number($('price').value),offerPrice:Number($('offerPrice').value),durationDays:Number($('days').value),deviceLimit:Math.max(1,Math.min(20,Number($('planDeviceLimit').value)||3)),displayOrder:Number($('order').value)||0,active:$('planActive').checked,shippingEnabled:$('shippingEnabled').checked,updatedAt:serverTimestamp()};if(!id||!data.name||data.price<0||data.offerPrice<0||data.durationDays<0){alert('Check plan values.');return;}await setDoc(doc(db,'plans',id),data,{merge:true});toast('Plan saved.');loadPlans();};}

function keyCode(){return `MEESHO-${crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase().match(/.{1,4}/g).join('-')}`;}
async function loadActivationKeys(){const [ks,ps]=await Promise.all([getDocs(query(collection(db,'activationKeys'),limit(500))),getDocs(query(collection(db,'plans'),limit(100)))]);const plans=ps.docs.filter(s=>!s.data().system).map(s=>({id:s.id,...s.data()}));const keys=ks.docs.filter(s=>!s.data().system);const rows=keys.map(s=>{const d=s.data();return `<tr><td><span class="key-code">${esc(s.id)}</span></td><td>${esc(d.targetEmail||'—')}</td><td>${esc(d.planName||d.planId||'—')}</td><td>${money(d.offerPrice??d.price)}</td><td>${badge(d.status||'AVAILABLE')}</td><td>${esc(dateText(d.keyExpiresAt))}</td><td><button class="deleteKey danger-outline" data-id="${esc(s.id)}">Delete</button></td></tr>`}).join('');$('activationKeys').innerHTML=`<div class="page-head"><div><h2>Activation Keys</h2><p class="muted">Keys are permanently bound to the customer Gmail.</p></div><button id="keysRefresh" class="ghost">Refresh</button></div><div class="panel form-panel"><form id="keyForm" class="form-grid"><label>Customer Gmail<input id="keyEmail" type="email" required placeholder="customer@gmail.com"></label><label>Plan<select id="keyPlan">${plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} — ${money(p.offerPrice??p.price)}</option>`).join('')}</select></label><label>Key Valid For (Days)<input id="keyValid" type="number" min="1" max="365" value="7"></label><div class="form-actions"><button class="primary small-btn" type="submit">Generate Activation Key</button></div></form></div><div class="panel"><table class="table"><thead><tr><th>Code</th><th>Gmail</th><th>Plan</th><th>Price</th><th>Status</th><th>Key Expiry</th><th>Action</th></tr></thead><tbody>${rows||'<tr><td colspan="7">No activation keys yet.</td></tr>'}</tbody></table></div>`;$('keysRefresh').onclick=loadActivationKeys;$('keyForm').onsubmit=async e=>{e.preventDefault();const email=$('keyEmail').value.trim().toLowerCase();const p=plans.find(x=>x.id===$('keyPlan').value);if(!email||!p){toast('Create a plan first.','error');return;}const code=keyCode();const now=new Date();const valid=Math.max(1,Math.min(365,Number($('keyValid').value)||7));await setDoc(doc(db,'activationKeys',code),{code,targetEmail:email,planId:p.id,planName:p.name,price:Number(p.price||0),offerPrice:Number(p.offerPrice??p.price??0),durationDays:Number(p.durationDays||0),shippingEnabled:p.shippingEnabled!==false,deviceLimit:Math.max(1,Math.min(20,Number(p.deviceLimit||3))),status:'AVAILABLE',keyExpiresAt:Timestamp.fromDate(new Date(now.getTime()+valid*86400000)),createdAt:serverTimestamp(),createdBy:auth.currentUser?.uid||''});toast(`Activation key created: ${code}`);navigator.clipboard?.writeText(code).catch(()=>{});loadActivationKeys();};document.querySelectorAll('.deleteKey').forEach(b=>b.onclick=async()=>{if(!confirm(`Delete activation key ${b.dataset.id}?`))return;await deleteDoc(doc(db,'activationKeys',b.dataset.id));toast('Activation key deleted.');loadActivationKeys();});}

async function loadMemberships(){const snap=await getDocs(query(collection(db,'customers'),limit(500)));const rows=snap.docs.filter(s=>!s.data().system).map(s=>{const d=s.data();return `<tr><td>${esc(s.id)}</td><td>${esc(d.planName||d.planId||'—')}</td><td>${badge(d.status||'NOT_ACTIVATED')}</td><td>${esc(dateText(d.startDate))}</td><td>${Number(d.durationDays||0)===0?'NEVER':esc(dateText(d.expiryDate))}</td><td>${esc(d.deviceLimit||3)}</td><td><button class="revokeMembership" data-email="${esc(s.id)}">${String(d.status||'').toUpperCase()==='REVOKED'?'Activate':'Revoke'}</button></td></tr>`}).join('');$('memberships').innerHTML=`<div class="page-head"><div><h2>Memberships</h2><p class="muted">Membership is stored under the customer email.</p></div><button id="membershipRefresh" class="ghost">Refresh</button></div><div class="panel"><table class="table"><thead><tr><th>Gmail</th><th>Plan</th><th>Status</th><th>Start</th><th>Expiry</th><th>Devices</th><th>Action</th></tr></thead><tbody>${rows||'<tr><td colspan="7">No customers yet.</td></tr>'}</tbody></table></div>`;$('membershipRefresh').onclick=loadMemberships;document.querySelectorAll('.revokeMembership').forEach(b=>b.onclick=async()=>{const ref=doc(db,'customers',b.dataset.email);const s=await getDoc(ref);if(!s.exists())return;const st=String(s.data().status||'').toUpperCase();await updateDoc(ref,{status:st==='REVOKED'?'ACTIVE':'REVOKED',updatedAt:serverTimestamp()});toast('Membership status updated.');loadMemberships();});}

async function loadDevices(){const cs=await getDocs(query(collection(db,'customers'),limit(500)));const out=[];for(const s of cs.docs.filter(x=>!x.data().system)){const d=s.data();let ds=[];try{ds=(await getDocs(query(collection(db,'customers',s.id,'devices'),limit(50)))).docs;}catch{}ds.forEach(x=>{const z=x.data();out.push({email:s.id,device:x.id,d:z,limit:Number(d.deviceLimit||3)});});}const rows=out.map(x=>`<tr><td>${esc(x.email)}</td><td>${esc(x.device)}</td><td>${esc(x.d.deviceLabel||'—')}</td><td>${esc(x.d.platform||'—')}</td><td>${esc(dateTimeText(x.d.lastActiveAt))}</td><td>${badge(x.d.status||'ACTIVE')}</td><td>${x.limit}</td><td><button class="deleteDevice danger-outline" data-email="${esc(x.email)}" data-device="${esc(x.device)}">Remove</button></td></tr>`).join('');$('devices').innerHTML=`<div class="page-head"><div><h2>Devices</h2><p class="muted">All device slots belong to the Gmail account.</p></div><button id="devicesRefresh" class="ghost">Refresh</button></div><div class="panel"><table class="table"><thead><tr><th>Gmail</th><th>Slot</th><th>Device</th><th>Platform</th><th>Last Active</th><th>Status</th><th>Limit</th><th>Action</th></tr></thead><tbody>${rows||'<tr><td colspan="8">No device records yet.</td></tr>'}</tbody></table></div>`;$('devicesRefresh').onclick=loadDevices;document.querySelectorAll('.deleteDevice').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this device slot?'))return;await deleteDoc(doc(db,'customers',b.dataset.email,'devices',b.dataset.device));toast('Device removed.');loadDevices();});}

async function loadSettings(){const s=await getDoc(doc(db,'settings','general'));const d=s.exists()?s.data():{};$('settings').innerHTML=`<div class="page-head"><div><h2>Settings</h2><p class="muted">Support and application settings. No payment/UPI system.</p></div></div><div class="panel"><div class="form-grid"><label>App Name<input id="appName" value="${esc(d.appName||'MEESHO A+ LISTING AUTOMATION PRO')}"></label><label>Brand Name<input id="brandName" value="${esc(d.brandName||'Sohel Enterprise')}"></label><label>Support Name<input id="supportName" value="${esc(d.supportName||'Sohel Rana')}"></label><label>Support Phone<input id="supportPhone" value="${esc(d.supportPhone||'')}"></label><label>WhatsApp<input id="whatsapp" value="${esc(d.whatsapp||'')}"></label><label>Support Email<input id="supportEmail" value="${esc(d.supportEmail||'')}"></label><div class="form-actions"><button id="saveSettings" class="primary small-btn">Save Settings</button></div></div></div>`;$('saveSettings').onclick=async()=>{await setDoc(doc(db,'settings','general'),{appName:$('appName').value.trim(),brandName:$('brandName').value.trim(),supportName:$('supportName').value.trim(),supportPhone:$('supportPhone').value.trim(),whatsapp:$('whatsapp').value.trim(),supportEmail:$('supportEmail').value.trim(),updatedAt:serverTimestamp()},{merge:true});toast('Settings saved.');};}

async function refresh(id){if(id==='dashboard')return loadDashboard();if(id==='customers')return loadCustomers();if(id==='plans')return loadPlans();if(id==='activationKeys')return loadActivationKeys();if(id==='memberships')return loadMemberships();if(id==='devices')return loadDevices();if(id==='settings')return loadSettings();}
async function refreshAll(){await loadDashboard();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=async()=>{nav(b.dataset.section);try{await refresh(b.dataset.section);}catch(e){console.error(e);toast(e.message||'Load failed','error');}});
$('googleLogin').onclick=async()=>{try{$('loginError').textContent='';await signInWithPopup(auth,provider);}catch(e){$('loginError').textContent=e.message||'Login failed.';}};
$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){$('loginView').classList.remove('hidden');$('adminView').classList.add('hidden');return;}try{if(!(await adminOK(u))){await signOut(auth);$('loginError').textContent='This Google account is not an authorized admin.';return;}$('adminEmail').textContent=u.email||'';$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');nav('dashboard');await loadDashboard();}catch(e){console.error(e);await signOut(auth);$('loginError').textContent='Admin verification failed: '+(e.message||'unknown error');}});
