import { initializeApp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import { getFirestore, collection, getDocs, doc, getDoc, setDoc, updateDoc, query, orderBy, limit, serverTimestamp, where } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app=initializeApp(firebaseConfig); const auth=getAuth(app); const db=getFirestore(app); const provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function show(id){document.querySelectorAll('.section').forEach(x=>x.classList.add('hidden')); $(id).classList.remove('hidden'); document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===id));}
async function isAdmin(user){const snap=await getDoc(doc(db,'admins',user.uid)); return snap.exists() && snap.data().active===true;}
function statusBadge(s){const c=(s||'').toLowerCase(); return `<span class="badge ${c==='active'?'active':c==='expired'?'expired':'pending'}">${esc(s||'UNKNOWN')}</span>`;}
async function loadDashboard(){
  const [u,p,m] = await Promise.all([getDocs(collection(db,'users')),getDocs(collection(db,'payments')),getDocs(collection(db,'memberships'))]);
  let active=0,expired=0,lifetime=0,pending=0; const now=Date.now();
  m.forEach(x=>{const d=x.data(); if(d.status==='ACTIVE')active++; if(d.status==='EXPIRED')expired++; if(String(d.planId||'').toLowerCase()==='lifetime')lifetime++;});
  p.forEach(x=>{if(x.data().status==='PENDING')pending++;});
  $('dashboard').innerHTML=`<h2>Dashboard</h2><div class="grid"><div class="stat">Users<b>${u.size}</b></div><div class="stat">Active Members<b>${active}</b></div><div class="stat">Expired<b>${expired}</b></div><div class="stat">Lifetime<b>${lifetime}</b></div><div class="stat">Pending Payments<b>${pending}</b></div></div><div class="panel"><div class="notice">Admin data is protected by Firestore Rules. Only UIDs listed in <b>admins/{uid}</b> with <b>active: true</b> can use this panel.</div></div>`;
}
async function loadUsers(){const snap=await getDocs(query(collection(db,'users'),limit(500)));let rows='';snap.forEach(s=>{const d=s.data();rows+=`<tr><td>${esc(d.name||d.displayName||'-')}</td><td>${esc(d.email||'-')}</td><td>${esc(d.planId||'-')}</td><td>${statusBadge(d.status||d.membershipStatus||'-')}</td><td>${esc(d.lastLoginAt?.toDate?.()?.toLocaleString?.()||'-')}</td><td class="row-actions"><button data-user="${s.id}" class="extend">Extend</button><button data-user="${s.id}" class="suspend">Suspend</button></td></tr>`});$('users').innerHTML=`<h2>Users</h2><div class="panel"><table class="table"><thead><tr><th>User</th><th>Email</th><th>Plan</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No users yet.</td></tr>'}</tbody></table></div>`;}
async function loadPlans(){const snap=await getDocs(collection(db,'plans'));let rows='';snap.forEach(s=>{const d=s.data();rows+=`<tr><td>${esc(s.id)}</td><td>${esc(d.name||'-')}</td><td>₹${esc(d.price??'-')}</td><td>${esc(d.durationDays??'∞')}</td><td>${statusBadge(d.active===false?'DISABLED':'ACTIVE')}</td></tr>`});$('plans').innerHTML=`<h2>Plans</h2><div class="panel"><table class="table"><thead><tr><th>ID</th><th>Name</th><th>Price</th><th>Days</th><th>Status</th></tr></thead><tbody>${rows||'<tr><td colspan="5">Create plans in Firestore first.</td></tr>'}</tbody></table></div>`;}
async function loadPayments(){const snap=await getDocs(query(collection(db,'payments'),orderBy('createdAt','desc'),limit(200)));let rows='';snap.forEach(s=>{const d=s.data();rows+=`<tr><td>${esc(d.userEmail||d.uid||'-')}</td><td>${esc(d.planId||'-')}</td><td>₹${esc(d.amount??'-')}</td><td>${statusBadge(d.status||'PENDING')}</td><td>${esc(d.utr||'-')}</td><td class="row-actions"><button data-pay="${s.id}" class="approve">Approve</button><button data-pay="${s.id}" class="reject">Reject</button></td></tr>`});$('payments').innerHTML=`<h2>Payments</h2><div class="panel"><table class="table"><thead><tr><th>User</th><th>Plan</th><th>Amount</th><th>Status</th><th>UTR</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No payment requests.</td></tr>'}</tbody></table></div>`;}
async function loadMemberships(){const snap=await getDocs(query(collection(db,'memberships'),limit(500)));let rows='';snap.forEach(s=>{const d=s.data();rows+=`<tr><td>${esc(d.uid||s.id)}</td><td>${esc(d.planId||'-')}</td><td>${statusBadge(d.status||'-')}</td><td>${esc(d.startDate?.toDate?.()?.toLocaleDateString?.()||'-')}</td><td>${esc(d.expiryDate?.toDate?.()?.toLocaleDateString?.()||'NEVER')}</td></tr>`});$('memberships').innerHTML=`<h2>Memberships</h2><div class="panel"><table class="table"><thead><tr><th>UID</th><th>Plan</th><th>Status</th><th>Start</th><th>Expiry</th></tr></thead><tbody>${rows||'<tr><td colspan="5">No memberships yet.</td></tr>'}</tbody></table></div>`;}
async function loadDevices(){const snap=await getDocs(query(collection(db,'devices'),limit(500)));let rows='';snap.forEach(s=>{const d=s.data();rows+=`<tr><td>${esc(d.uid||'-')}</td><td>${esc(d.deviceLabel||d.platform||'-')}</td><td>${esc(d.lastActiveAt?.toDate?.()?.toLocaleString?.()||'-')}</td><td>${statusBadge(d.status||'ACTIVE')}</td></tr>`});$('devices').innerHTML=`<h2>Devices</h2><div class="panel"><table class="table"><thead><tr><th>User</th><th>Device</th><th>Last Active</th><th>Status</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No device sessions yet.</td></tr>'}</tbody></table></div>`;}
async function loadSettings(){const s=await getDoc(doc(db,'settings','general'));const d=s.exists()?s.data():{};$('settings').innerHTML=`<h2>Settings</h2><div class="panel"><div class="form"><label>Support Number<input id="supportPhone" value="${esc(d.supportPhone||'')}"></label><label>WhatsApp Number<input id="whatsapp" value="${esc(d.whatsapp||'')}"></label><label>Support Email<input id="supportEmail" value="${esc(d.supportEmail||'')}"></label><label>UPI ID<input id="upiId" value="${esc(d.upiId||'')}"></label><button id="saveSettings" class="primary">Save Settings</button></div></div>`;$('saveSettings').onclick=async()=>{await setDoc(doc(db,'settings','general'),{supportPhone:$('supportPhone').value.trim(),whatsapp:$('whatsapp').value.trim(),supportEmail:$('supportEmail').value.trim(),upiId:$('upiId').value.trim(),updatedAt:serverTimestamp()},{merge:true});alert('Settings saved.');};}
async function refresh(section){if(section==='dashboard')await loadDashboard();if(section==='users')await loadUsers();if(section==='plans')await loadPlans();if(section==='payments')await loadPayments();if(section==='memberships')await loadMemberships();if(section==='devices')await loadDevices();if(section==='settings')await loadSettings();}
document.querySelectorAll('.nav').forEach(n=>n.onclick=async()=>{show(n.dataset.section);await refresh(n.dataset.section);});
$('googleLogin').onclick=async()=>{try{$('loginError').textContent='';await signInWithPopup(auth,provider);}catch(e){$('loginError').textContent=e.message||'Login failed.';}};
$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){$('loginView').classList.remove('hidden');$('adminView').classList.add('hidden');return;}try{if(!(await isAdmin(user))){await signOut(auth);$('loginError').textContent='This Google account is not an authorized admin.';return;}$('adminEmail').textContent=user.email||'';$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');show('dashboard');await loadDashboard();}catch(e){await signOut(auth);$('loginError').textContent='Admin verification failed: '+(e.message||'unknown error');}});
